hosts = {
	"kali"			=> {"units" => 1, "mem" => "2048", "box" => "tonijaaskelainen/kali", "ssh_username" => "root", "ssh_password" => "toor"},
	"ms2"			=> {"units" => 1, "mem" =>  "512", "box" => "tonijaaskelainen/ms2",  "ssh_username" => "msfadmin", "ssh_password" => "msfadmin"},

	"centos-7"		=> {"units" => 0, "mem" =>  "512", "box" => "centos/7"},
	"centos-6"		=> {"units" => 0, "mem" =>  "512", "box" => "centos/6"},
	"ubuntu-xenial"		=> {"units" => 3, "mem" =>  "512", "box" => "bento/ubuntu-16.04"},
	"ubuntu-trusty"		=> {"units" => 0, "mem" =>  "512", "box" => "bento/ubuntu-14.04"},
	"ubuntu-precise"	=> {"units" => 0, "mem" =>  "512", "box" => "bento/ubuntu-12.04"},
}

Vagrant.configure(2) do |config|
	hosts.each do |distro, v|

		# Create distro units (instances).
		(1..v["units"]).each do |i|

			# Set variable to be used as *both* the vagrant machine
			# name and the hostname.
			name = "%s-%d" % [distro, i]

			config.vm.define name do |u|
				u.vm.box = v["box"]
				u.vm.hostname = name
				u.vm.network "private_network", type: "dhcp"

				# If provided above, use username/password auth instead of key-based
				if v.key?("ssh_username")
					u.ssh.username   = v["ssh_username"]
					u.ssh.password   = v["ssh_password"]
				end


				u.vm.provider "virtualbox" do |vb|
					vb.linked_clone = true
					vb.gui = false
					vb.memory = v["mem"]
				end
			end
		end
	end
end
