hosts = {
	"kali"			=> {"units" => 1, "mem" => "2048", "box" => "Sliim/kali-2017.2-light-amd64", "key" => "pentest-env"},
	"ms2"			=> {"units" => 1, "mem" =>  "512", "box" => "Sliim/metasploitable2", "key" => "pentest-env"},

	"centos-7"		=> {"units" => 1, "mem" =>  "512", "box" => "centos/7"},
	"centos-6"		=> {"units" => 1, "mem" =>  "512", "box" => "centos/6"},
	"ubuntu-xenial"		=> {"units" => 1, "mem" =>  "512", "box" => "bento/ubuntu-16.04"},
	"ubuntu-trusty"		=> {"units" => 1, "mem" =>  "512", "box" => "bento/ubuntu-14.04"},
}

Vagrant.configure(2) do |config|
	hosts.each do |distro, v|

		# Create distro units (instances).
		(1..v["units"]).each do |i|

			# Set variable to be used as *both* the vagrant machine
			# name and the hostname.
			name = "%s-%d" % [distro, i]

			config.vm.define name do |u|
				u.vm.box = v["box"]
				u.vm.hostname = name
				u.vm.network "private_network", type: "dhcp"

				# If provided above, use username/password auth instead of key-based
				if v.key?("key")
					u.ssh.username   = "root"
					u.ssh.private_key_path   = v["key"]
				end


				u.vm.provider "virtualbox" do |vb|
					vb.linked_clone = true
					vb.gui = false
					vb.memory = v["mem"]
				end
			end
		end
	end
end
