Vagrant.configure(2) do |config|
	name = "desktop"
	config.vm.define name do |d|
		d.vm.box = "box-cutter/ubuntu1404-desktop"
		d.vm.hostname = name
		d.vm.network "private_network", ip: "10.10.10.11"
	end

	name = "server"
	config.vm.define name do |s|
		s.vm.box = "ubuntu/trusty64"
		s.vm.hostname = name
		s.vm.network "private_network", ip: "10.10.10.12"
	end
end
