$nubuntu = 1
$ncentos = 1

Vagrant.configure(2) do |config|

	# TODO: metasploitable 2
	# possible candidate: https://github.com/citizen-stig/dockermutillidae

	# FIXME: when multiple containers spawned, all get same hostname!

	# kali
	name = "kali"
	config.vm.define name do |k|
		k.vm.provider "docker" do |d|
			d.build_dir = "docker/kali"
			d.create_args = ["-i", "-t", "--hostname", name]
		end
	end

	# ubuntu
	(1..$nubuntu).each do |i|
		name = "%s%d" % ["ubuntu", i]
		config.vm.define name do |u|
			u.vm.provider "docker" do |d|
				d.build_dir = "docker/ubuntu"
				d.create_args = ["-i", "-t", "--hostname", name]
			end
		end
	end

	# centos
	(1..$ncentos).each do |i|
		name = "%s%d" % ["centos", i]
		config.vm.define name do |c|
			c.vm.provider "docker" do |d|
				d.build_dir = "docker/centos"
				d.create_args = ["-i", "-t", "--hostname", name]
			end
		end
	end

end
