Vagrant.configure(2) do |config|
	config.vm.box = "living42/openwrt-15.05-x86"
	# not working, so disable
	config.vm.synced_folder ".", "/vagrant", disabled: true

	config.vm.provider "virtualbox" do |vb|
		vb.gui = false
		vb.memory = "64"
		# avoid installing non-free extras
		vb.customize ["modifyvm", :id, "--usb", "off"]
	end

	config.vm.provision "shell", inline: <<-END
		usermod -s /bin/bash root
		opkg update
		opkg install vim-full python-light ip
	END
end
