NMACHINES=2
LAN_PREFIX = "10.13.37"

# Enable extra disk (for testing partitioning, LVM, etc)
# See https://github.com/kusnier/vagrant-persistent-storage
DISK = true
DISK_MB = 100
DISK_PLUGIN = "vagrant-persistent-storage"

# via http://stackoverflow.com/a/28801317
unless Vagrant.has_plugin?(DISK_PLUGIN)
	# install plugin
	if system "vagrant plugin install #{DISK_PLUGIN}"
		# if plugin installed successfully, restart vagrant (with plugin now available)
		exec "vagrant #{ARGV.join(' ')}"
	end
end


Vagrant.configure(2) do |config|
	(1..NMACHINES).each do |i|
		name = "box#{i}"

		config.vm.define name do |node|
			node.vm.box = "centos/7"
			node.vm.hostname = name
			node.vm.network "private_network", ip: "#{LAN_PREFIX}.#{10 + i}"

			if DISK
				node.persistent_storage.enabled = true
				node.persistent_storage.use_lvm = false
				node.persistent_storage.format = false
				node.persistent_storage.manage = false
				node.persistent_storage.size = DISK_MB
				node.persistent_storage.location = "#{name}_extradisk.vdi"
			end

			#node.vm.provision "shell", inline: <<-SHELL
			#	yum install -y epel-release
			#	yum install -y bind-utils docker git mtr tmux tree vim bzip2
			#SHELL
		end
	end
end
